### ISSUE TITLE
bug: Installation Issues

### ISSUE THREAD

**Issue by mrcnski** [machshev/bible-modules#1]
### Description of the bug

Thank you for this resource! Unfortunately I get an error when running `pdm install`.

If it matters, I installed `pdx` through Homebrew, because the step `pip3 install pdx` gave me an error about externally-managed environments.

### To Reproduce

```
I ran `pdm install` with `PDM, version 2.19.2`.
```

### Full traceback

<details><summary>Full traceback</summary>

```python
WARNING: Lockfile is generated on an older version of PDM
WARNING: Lockfile hash doesn't match pyproject.toml, packages may be outdated
Updating the lock file...
DEPRECATED: `cross_platform` strategy is deprecated in favor of the new lock targets.
See docs: http://pdm-project.org/en/latest/usage/lock-targets/
WARNING: Project requires a python version of >=3.12, The virtualenv is being created for you as it cannot be matched to the right version.
INFO: python.use_venv is on, creating a virtualenv for this project...
Virtualenv is created successfully at /Users/marcin/Sync/Repos/github.com/machshev/bible-modules/.venv
Changes are written to pdm.lock.
  0:00:19 🔒 Lock successful.  

STATUS: Resolving packages from lockfile...
Synchronizing working set with resolved packages: 125 to add, 0 to update, 0 to remove

  ✔ Install setuptools 70.0.0 successful
  ✔ Install annotated-types 0.7.0 successful
  ✔ Install colorama 0.4.6 successful
  ✔ Install blacken-docs 1.16.0 successful
  ✔ Install appdirs 1.4.4 successful
  ✔ Install docstring-to-markdown 0.15 successful
  ✔ Install click 8.1.7 successful
  ✔ Install certifi 2024.6.2 successful
  ✔ Install dparse 0.6.4b0 successful
  ✔ Install autopep8 2.0.4 successful
  ✔ Install editables 0.5 successful
  ✔ Install ansimarkup 1.5.0 successful
  ✔ Install cattrs 23.2.3 successful
  ✔ Install attrs 23.2.0 successful
  ✔ Install astroid 3.2.2 successful
  ✔ Install ghp-import 2.1.0 successful
  ✔ Install execnet 2.1.1 successful
  ✔ Install failprint 1.0.2 successful
  ✔ Install git-changelog 2.5.2 successful
  ✔ Install flake8 7.0.0 successful
  ✔ Install gitdb 4.0.11 successful
  ✔ Install htmlmin2 0.1.13 successful
  ✔ Install iniconfig 2.0.0 successful
  ✔ Install duty 1.4.0 successful
  ✔ Install dill 0.3.8 successful
  ✔ Install csscompressor 0.9.5 successful
  ✔ Install authlib 1.3.0 successful
  ✔ Install gitpython 3.1.43 successful
  ✔ Install idna 3.7 successful
  ✔ Install importlib-metadata 7.1.0 successful
  ✔ Install griffe 0.45.2 successful
  ✔ Install lsprotocol 2023.0.1 successful
  ✔ Install markdown-callouts 0.4.0 successful
  ✔ Install isort 5.13.2 successful
  ✔ Install marshmallow 3.21.2 successful
  ✔ Install mccabe 0.7.0 successful
  ✔ Install jinja2 3.1.4 successful
  ✔ Install markdown-exec 1.8.3 successful
  ✔ Install mdurl 0.1.2 successful
  ✔ Install markdown 3.6 successful
  ✔ Install mergedeep 1.3.4 successful
  ✔ Install markdown-it-py 3.0.0 successful
  ✔ Install mkdocs-coverage 1.0.0 successful
  ✔ Install mkdocs-autorefs 1.0.1 successful
  ✔ Install mkdocs-get-deps 0.2.0 successful
  ✔ Install mkdocs-literate-nav 0.6.1 successful
  ✔ Install mkdocs-git-committers-plugin-2 2.3.0 successful
  ✔ Install mkdocs-gen-files 0.5.0 successful
  ✔ Install mkdocs-material-extensions 1.3.1 successful
  ✔ Install mypy-extensions 1.0.0 successful
  ✔ Install mkdocstrings 0.25.1 successful
  ✔ Install mkdocs-minify-plugin 0.8.0 successful
  ✔ Install packaging 24.0 successful
  ✔ Install jsmin 3.0.1 successful
  ✔ Install parso 0.8.4 successful
  ✔ Install pathspec 0.12.1 successful
  ✔ Install mkdocstrings-python 1.10.3 successful
  ✔ Install platformdirs 4.2.2 successful
  ✔ Install ptyprocess 0.7.0 successful
  ✔ Install pluggy 1.5.0 successful
  ✔ Install mkdocs 1.6.0 successful
  ✔ Install black 24.4.2 successful
  ✔ Install pycodestyle 2.11.1 successful
  ✔ Install pycparser 2.22 successful
  ✔ Install paginate 0.5.6 successful
  ✔ Install pydocstyle 6.3.0 successful
  ✔ Install pyflakes 3.2.0 successful
  ✔ Install pandas-stubs 2.2.2.240514 successful
  ✔ Install pyhamcrest 2.1.0 successful
  ✔ Install pymdown-extensions 10.8.1 successful
  ✔ Install pytest-cov 5.0.0 successful
  ✔ Install pytest-randomly 3.15.0 successful
  ✔ Install pytest 8.2.1 successful
  ✔ Install pytest-xdist 3.6.1 successful
  ✔ Install python-lsp-jsonrpc 1.1.2 successful
  ✔ Install python-dateutil 2.9.0.post0 successful
  ✔ Install pylint 3.2.2 successful
  ✔ Install python-lsp-ruff 2.2.1 successful
  ✔ Install pytoolconfig 1.3.1 successful
  ✔ Install python-lsp-server 1.11.0 successful
  ✔ Install pyyaml-env-tag 0.1 successful
  ✔ Install charset-normalizer 3.3.2 successful
  ✔ Install pygments 2.18.0 successful
  ✔ Install requests 2.32.3 successful
  ✔ Install rope 1.13.0 successful
  ✔ Install rich 13.7.1 successful
  ✔ Install babel 2.15.0 successful
  ✔ Install safety-schemas 0.0.2 successful
  ✔ Install safety 3.2.0 successful
  ✔ Install shellingham 1.5.4 successful
  ✔ Install semver 3.0.2 successful
  ✔ Install six 1.16.0 successful
  ✔ Install smmap 5.0.1 successful
  ✔ Install tomli 2.0.1 successful
  ✔ Install snowballstemmer 2.2.0 successful
  ✔ Install jedi 0.19.1 successful
  ✔ Install tomlkit 0.12.5 successful
  ✔ Install typer 0.12.3 successful
  ✔ Install types-markdown 3.6.0.20240316 successful
  ✔ Install types-pyyaml 6.0.12.20240311 successful
  ✔ Install types-requests 2.32.0.20240602 successful
  ✔ Install types-pytz 2024.1.0.20240417 successful
  ✔ Install typing-extensions 4.12.1 successful
  ✔ Install urllib3 2.2.1 successful
  ✔ Install tzdata 2024.1 successful
  ✔ Install pytz 2024.1 successful
  ✔ Install whatthepatch 1.0.5 successful
  ✔ Install zipp 3.19.1 successful
  ✔ Install yapf 0.40.2 successful
  ✔ Install markupsafe 2.1.5 successful
  ✔ Install pydantic 2.7.2 successful
  ✔ Install mypy 1.10.0 successful
  ✔ Install ujson 5.10.0 successful
  ✔ Install watchdog 4.0.1 successful
  ✔ Install ruamel-yaml 0.18.6 successful
  ✔ Install cryptography 42.0.7 successful
  ✖ Install cffi 1.16.0 failed
  ✔ Install ruff 0.4.7 successful
  ✔ Install coverage 7.5.3 successful
  ✔ Install pyyaml 6.0.1 successful
  ✔ Install mkdocs-material 9.5.25 successful
  ✔ Install regex 2024.5.15 successful
  ✖ Install pydantic-core 2.18.3 failed
  ✔ Install numpy 1.26.4 successful
  ✔ Install pandas 2.2.2 successful
  ✖ Install cffi 1.16.0 failed
  ✖ Install pydantic-core 2.18.3 failed

ERRORS:
add cffi failed:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py", 
line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/installers/synchronizers.py", line 29, in install_candidate
    self.manager.install(can)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ~~~~~~~~~~~~~~^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/models/candidates.py", line 411, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/wheel.py", line 26, in build
    filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pyproject_hooks/_impl.py", line 256, in build_wheel
    return self._call_hook(
           ~~~~~~~~~~~~~~~^
        "build_wheel",
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        },
        ^^
    )
    ^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pyproject_hooks/_impl.py", line 392, in _call_hook
    self._subprocess_runner(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        ,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cwd=self.source_dir,
        ^^^^^^^^^^^^^^^^^^^^
        extra_environ=extra_environ,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 281, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 128, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:
                                                     ^
src/c/_cffi_backend.c:6121:9: error: call to undeclared function '_PyErr_WriteUnraisableMsg'; ISO C99 and later do not support implicit 
function declarations [-Wimplicit-function-declaration]
        _PyErr_WriteUnraisableMsg(PyText_AS_UTF8(s), NULL);
        ^
src/c/_cffi_backend.c:6121:9: note: did you mean 'PyErr_WriteUnraisable'?
/opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/pyerrors.h:233:18: note: 'PyErr_WriteUnraisable' 
declared here
PyAPI_FUNC(void) PyErr_WriteUnraisable(PyObject *);
                 ^
1 warning and 1 error generated.
error: command '/usr/bin/clang' failed with exit code 1
add pydantic-core failed:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.13/3.13.0_1/Frameworks/Python.framework/Versions/3.13/lib/python3.13/concurrent/futures/thread.py", 
line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/installers/synchronizers.py", line 29, in install_candidate
    self.manager.install(can)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/installers/manager.py", line 33, in install
    prepared.build(),
    ~~~~~~~~~~~~~~^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/models/candidates.py", line 411, in build
    self._cached = Path(builder.build(build_dir, metadata_directory=self._metadata_dir))
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 84, in wrapper
    return func(*args, **kwargs)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/wheel.py", line 26, in build
    filename = self._hook.build_wheel(out_dir, self.config_settings, metadata_directory)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pyproject_hooks/_impl.py", line 256, in build_wheel
    return self._call_hook(
           ~~~~~~~~~~~~~~~^
        "build_wheel",
        ^^^^^^^^^^^^^^
    ...<4 lines>...
        },
        ^^
    )
    ^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pyproject_hooks/_impl.py", line 392, in _call_hook
    self._subprocess_runner(
    ~~~~~~~~~~~~~~~~~~~~~~~^
        ,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        cwd=self.source_dir,
        ^^^^^^^^^^^^^^^^^^^^
        extra_environ=extra_environ,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 281, in subprocess_runner
    return log_subprocessor(cmd, cwd, extra_environ=env)
  File "/Users/marcin/.local/pipx/venvs/pdm/lib/python3.13/site-packages/pdm/builders/base.py", line 128, in log_subprocessor
    raise build_error(e) from None
pdm.exceptions.BuildError: Build backend raised error: Showing the last 10 lines of the build output:

  --- stderr
  error: the configured Python interpreter version (3.13) is newer than PyO3's maximum supported version (3.12)
  = help: please check if an updated version of PyO3 is available. Current version: 0.21.2
  = help: set PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1 to suppress this check and build anyway using the stable ABI
warning: build failed, waiting for other jobs to finish...
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `env -u CARGO MACOSX_DEPLOYMENT_TARGET="11.0" 
PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/Users/marcin/Sync/Repos/github.com/machshev/bible-modules/.venv/bin/python" 
PYTHON_SYS_EXECUTABLE="/Users/marcin/Sync/Repos/github.com/machshev/bible-modules/.venv/bin/python" "cargo" "rustc" "--features" 
"pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" 
"/private/var/folders/2y/kvzrb0dn2yd84061bz0jwdgh0000gn/T/pdm-build-3avt88fy/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib" "--" 
"-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" 
"link-args=-Wl,-install_name,@rpath/pydantic_core._pydantic_core.cpython-313-darwin.so"`
Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/marcin/Sync/Repos/github.com/machshev/bible-modules/.venv/bin/python', 
'--compatibility', 'off'] returned non-zero exit status 1

  0:00:55 ✖ Some package operations failed. 2/2

See /Users/marcin/Library/Logs/pdm/pdm-install-78r76uku.log for detailed debug log.
[InstallationError]: Some package operations failed.
WARNING: Add '-v' to see the detailed traceback
```

</details>

### Environment information

```bash
abm-tools --debug-info  # | xclip -selection clipboard
```

PASTE OUTPUT HERE

**Comment by mrcnski** [comment]
Awesome, it works! Thank you for that.

By the way, do you have a recommendation for Mac software that can open these modules, and in particular the Syriac lexicon module?
